---
- name: dev machines provisioned
  hosts: dev
  become: yes
  vars:
    maven_major_version: 3
    maven_version: 3.8.6
  tasks:
    - name: include deploy_tools_tasks file
      include_tasks: deploy_tools_tasks.yml

- name: dev machines provisioned
  hosts: jenkins
  become: yes
  vars:
    maven_major_version: 3
    maven_version: 3.8.6
  tasks:
    - name: include deploy_tools_tasks file
      include_tasks: deploy_tools_tasks.yml

