---
- block:
  - name: install repo
    get_url:
      url: http://pkg.jenkins.io/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo     
      validate_certs: no
  - name: importer jenkins key depuis url
    ansible.builtin.rpm_key: 
      state: present
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
      validate_certs: no
  - name: yum update
    yum:
      name: '*'
      state: latest

  - name: Install java
    yum:
      name: java-11-openjdk-devel
      state: present

  - name: Install jenkins
    yum:
      name: jenkins
      state: latest
  - name: daemon-reload to pick up config changes
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: Start jenkins
    ansible.builtin.systemd:
      name: jenkins
      state: started
