---
- name: staging server configured
  hosts: staging
  become: yes
  tasks: 
  - name: docker installed
    include_tasks: docker_tasks.yml
  - name: add dockeruser to docker group
    user: 
      name: dockeruser
      groups: docker
      append: yes
  - name: add vagrant to docker group
    user:
      name: vagrant
      groups: docker
      append: yes

